implements ipns
FlashWeb3/flash-cli pull request #7
Opened 2023-06-19 20:09 UTC by aarontravass

closes #5

2023-06-21 05:24 UTC, talentlessguy requested changes

2023-06-21 05:24 UTC, talentlessguy commented on flash.ts
> +cli
let's do it like this:

1) file found -> fallback to env var
2) otherwise throw "Missing IPNS key"

2023-06-21 18:23 UTC, talentlessguy requested changes

2023-06-21 18:23 UTC, talentlessguy commented on package.json
> +    "lint": "eslint --no-error-on-unmatched-pattern . --ext=ts",
why this `no-error` flag?

2023-06-21 18:29 UTC, talentlessguy requested changes

2023-06-21 19:48 UTC, aarontravass commented on package.json
> +    "lint": "eslint --no-error-on-unmatched-pattern . --ext=ts",
https://eslint.org/docs/latest/use/command-line-interface#--no-error-on-unmatched-pattern 
if for some reason the script fails if it does not find a file, this will prevent it from exiting

2023-06-21 19:53 UTC, aarontravass commented on utils/ipns.ts
> +  const name = await Name.from(Uint8Array.from(Buffer.from(privKey!, 'hex')))
I don't think you can convert hex to ArrayBuffer without using some custom fns. See https://stackoverflow.com/questions/43131242/how-to-convert-a-hexadecimal-string-of-data-to-an-arraybuffer-in-javascript

2023-06-24 07:31 UTC, talentlessguy requested changes

2023-06-24 07:31 UTC, talentlessguy commented on flash.ts
> +            'IPNS value is taken from config and should not be supplied via cmd'
why not allow user to supply via cmd as well?

2023-06-24 07:31 UTC, talentlessguy commented on flash.ts
> +                value: ipnsValue || ''
we can have `process.env.FLASH_W3NAME_IPNS` as well

2023-06-24 07:31 UTC, talentlessguy commented on package.json
> +    "lint": "eslint --no-error-on-unmatched-pattern . --ext=ts",
it should error if it doesn't find the files, that's an unexpected behaviour

2023-06-28 05:32 UTC, talentlessguy requested changes

2023-06-28 05:32 UTC, talentlessguy commented on flash.ts
> +        break
you can save a line by doing a `return await createIPNS(ipnsValue)`

2023-06-28 17:05 UTC, talentlessguy approved these changes

2023-06-28 17:05 UTC, merged